# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: cnysten <cnysten@student.hive.fi>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/01/27 10:18:02 by cnysten           #+#    #+#              #
#    Updated: 2022/01/27 10:22:07 by cnysten          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = arg_printer

TEST_SRCS = arg_printer.c

all: $(NAME)

$(NAME): $(TEST_SRCS)
	gcc -o $(NAME) $(TEST_SRCS)

clean:

fclean: clean

re: fclean all
